### ISSUE TITLE
ConnectionError during Wikihow EN

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#122]
https://farm.openzim.org/pipeline/ad8f00f13cf0d042e9699326/debug

[IMG-T-2::2022-03-24 19:20:22,978] DEBUG:Attempting download of S3::https/www.wikihow.com/images/thumb/6/6c/Have-a-Good-Night-Sleep-in-a-Slumber-Party-Step-15-Version-2.jpg/-crop-127-140-127px-Have-a-Good-Night-Sleep-in-a-Slumber-Party-Step-15-Version-2.jpg into ZIM::images/3100328163--crop-127-140-127px-Have-a-Good-Night-Sleep-in-a-Slumber-Party-Step-15-Version-2.webp
[IMG-T-3::2022-03-24 19:20:23,123] DEBUG:Attempting download of S3::https/www.wikihow.com/images/thumb/9/92/Pack-For-a-Sleepover-Step-10-Version-2.jpg/-crop-127-140-127px-Pack-For-a-Sleepover-Step-10-Version-2.jpg into ZIM::images/2581016926--crop-127-140-127px-Pack-For-a-Sleepover-Step-10-Version-2.webp
[MainThread::2022-03-24 19:20:32,884] ERROR:Interrupting process due to error: HTTPSConnectionPool(host='www.wikihow.health', port=443): Max retries exceeded with url: /Help-an-Autistic-Family-Member-Cope-with-Home-Quarantine (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9d7d2c64c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[MainThread::2022-03-24 19:20:32,885] ERROR:HTTPSConnectionPool(host='www.wikihow.health', port=443): Max retries exceeded with url: /Help-an-Autistic-Family-Member-Cope-with-Home-Quarantine (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9d7d2c64c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9d7d2c64c0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.wikihow.health', port=443): Max retries exceeded with url: /Help-an-Autistic-Family-Member-Cope-with-Home-Quarantine (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9d7d2c64c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.1.0-py3.8.egg/wikihow2zim/scraper.py", line 989, in run
    self.scrape_articles()
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.1.0-py3.8.egg/wikihow2zim/scraper.py", line 517, in scrape_articles
    if not self.scrape_article(article):
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.1.0-py3.8.egg/wikihow2zim/scraper.py", line 619, in scrape_article
    soup, _ = get_soup(f"/{article}")
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.1.0-py3.8.egg/wikihow2zim/utils.py", line 149, in get_soup
    content, paths = fetch(path, **params)
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.1.0-py3.8.egg/wikihow2zim/utils.py", line 77, in fetch
    resp = session.get(get_url(path, **params), params=params)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.wikihow.health', port=443): Max retries exceeded with url: /Help-an-Autistic-Family-Member-Cope-with-Home-Quarantine (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9d7d2c64c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[MainThread::2022-03-24 19:20:32,890] DEBUG:shutting down executor IMG-T- with wait=False
[MainThread::2022-03-24 19:20:32,890] DEBUG:shutting down executor VID-T- with wait=False
[MainThread::2022-03-24 19:20:32,892] DEBUG:Removing /output/www.wikihow.com_xef4rw2r
[MainThread::2022-03-24 19:20:32,904] DEBUG:Images 2726/2755
[MainThread::2022-03-24 19:20:32,904] DEBUG:Images 2727/2755
[MainThread::2022-03-24 19:20:32,904] DEBUG:Images 2728/2755
[MainThread::2022-03-24 19:20:32,904] DEBUG:Images 2729/2755
[MainThread::2022-03-24 19:20:32,904] DEBUG:Images 2730/2755
[MainThread::2022-03-24 19:20:32,904] DEBUG:Images 2731/2755
[MainThread::2022-03-24 19:20:32,904] DEBUG:Images 2732/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2733/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2734/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2735/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2736/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2737/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2738/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2739/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2740/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2741/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2742/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2743/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2744/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2745/2755
[MainThread::2022-03-24 19:20:32,905] DEBUG:Images 2746/2755
[MainThread::2022-03-24 19:20:32,906] DEBUG:Images 2747/2755
[MainThread::2022-03-24 19:20:32,906] DEBUG:Images 2748/2755
[MainThread::2022-03-24 19:20:32,906] DEBUG:Images 2749/2755
[MainThread::2022-03-24 19:20:32,906] DEBUG:Images 2750/2755
[MainThread::2022-03-24 19:20:32,906] DEBUG:Images 2751/2755
[MainThread::2022-03-24 19:20:32,906] DEBUG:Images 2752/2755
[MainThread::2022-03-24 19:20:32,906] DEBUG:Images 2753/2755
[MainThread::2022-03-24 19:20:32,906] DEBUG:Images 2754/2755
[MainThread

**Comment by rgaudin** [comment]
Hum, I wonder why the domain to the failing connection is `www.wikihow.health`…

**Comment by kelson42** [comment]
@rgaudin Yes... really strange

**Comment by rgaudin** [comment]
We'd probably have better luck (and less maintenance) using [backoff](https://github.com/litl/backoff) to orchestrate our retries. It's a lot more flexible that urllib's mechanism and simpler than reimplementing obviously. If proven successful here, we could maybe replace the urlib version we have on scraperlib as well.

**Comment by kelson42** [comment]
@rgaudin I wonder if we should still do something, or do more, on this tocket?

**Comment by rgaudin** [comment]
This is anterior to the keepalive change. It may not be required anymore. Closing. We can still reopen if the problem appears again

**Comment by rgaudin** [comment]
Not connections error per say but 503 errors happens from time to time, especially on long-lasting runs. We need at least a pause+retry on 503 errors instead of just giving up.
