### ISSUE TITLE
wikiHow EN doesn't pass DOM Integrity Check anymore

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#129]
```
[MainThread::2022-05-21 18:35:10,692] INFO:testing S3 Optimization Cache credentials
[MainThread::2022-05-21 18:35:13,594] INFO:Starting scraper with:
  language: English (www.wikihow.com)
  output_dir: /output
  build_dir: /output/www.wikihow.com_8iwrvubm
  missing tolerance: 0%
  single_category: None
  categories: all
  using cache: s3.us-west-1.wasabisys.com with bucket: org-kiwix-wikihow
[MainThread::2022-05-21 18:35:13,595] INFO:Ensuring source site DOM Integrity
[MainThread::2022-05-21 18:35:13,595] DEBUG:> checking CategoryListing
[MainThread::2022-05-21 18:35:14,523] ERROR:FAILED. An error occurred: No links in #catlist_container
[MainThread::2022-05-21 18:35:14,523] ERROR:No links in #catlist_container
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.1.0-py3.8.egg/wikihow2zim/entrypoint.py", line 225, in main
    sys.exit(scraper.run())
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.1.0-py3.8.egg/wikihow2zim/scraper.py", line 921, in run
    self.check_dom_integrity()
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.1.0-py3.8.egg/wikihow2zim/scraper.py", line 855, in check_dom_integrity
    raise DomIntegrityError("No links in #catlist_container")
wikihow2zim.scraper.DomIntegrityError: No links in #catlist_container
```

From https://farm.openzim.org/pipeline/cd5de1784190c1163d039826/debug

**Comment by rgaudin** [comment]
Again, please use better titles for issues. This one is pretty clear: the DOM has changed on wikiHow EN and the scraper halts itself.

**Comment by rgaudin** [comment]
EN added a new Top categories on top of CategoryListing.

Fixed the selector to match the other links on regular and EN.

<img width="1098" alt="Screen Shot 2022-05-25 at 15 38 58" src="https://user-images.githubusercontent.com/57929/170310238-942981df-d113-4c8b-8369-5bd6457c0cb5.png">
