### ISSUE TITLE
Prevent duplicate categories/articles

### ISSUE THREAD

**Issue by rgaudin** [openzim/wikihow#134]
Should an article (I suppose) or a category (as described below) be referenced twice in a way that will be normalized to the same URL, we end up we a duplicate ZIM entry.

Here:

- Category: `Arbeit & Arbeiten`
- Category: `Arbeit-&-Arbeiten`

from [wikihow_de_all](https://farm.openzim.org/pipeline/1db100d0a26b4df43afc2e26/debug)

```
[MainThread::2022-07-30 12:31:47,239] ERROR:Interrupting process due to error: Impossible to add C/Kategorie:Arbeit-&-Arbeiten
  dirent's title to add is : Arbeit & Arbeiten - wikiHow
  existing dirent's title is : Arbeit & Arbeiten - wikiHow

[MainThread::2022-07-30 12:31:47,239] ERROR:Impossible to add C/Kategorie:Arbeit-&-Arbeiten
  dirent's title to add is : Arbeit & Arbeiten - wikiHow
  existing dirent's title is : Arbeit & Arbeiten - wikiHow
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.0-py3.8.egg/wikihow2zim/scraper.py", line 1001, in run
    self.scrape_categories()
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.0-py3.8.egg/wikihow2zim/scraper.py", line 530, in scrape_categories
    self.scrape_category(category)
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.0-py3.8.egg/wikihow2zim/scraper.py", line 534, in scrape_category
    nb_pages = self.scrape_category_page(category, page_num=1)
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.0-py3.8.egg/wikihow2zim/scraper.py", line 603, in scrape_category_page
    self.creator.add_item_for(
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 181, in add_item_for
    self.add_item(StaticItem(**kwargs), callback)
  File "/usr/local/lib/python3.8/site-packages/zimscraperlib/zim/creator.py", line 200, in add_item
    super().add_item(item)
  File "libzim/libzim.pyx", line 322, in libzim._Creator.add_item
RuntimeError: Impossible to add C/Kategorie:Arbeit-&-Arbeiten
  dirent's title to add is : Arbeit & Arbeiten - wikiHow
  existing dirent's title is : Arbeit & Arbeiten - wikiHow
```

**Comment by rgaudin** [comment]
Fixed via ea7b974
