### ISSUE TITLE
Scraping broken 

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#145]
See https://farm.openzim.org/pipeline/ee9f0edf8922d643041e9a36/debug

```
[MainThread::2023-01-06 21:44:14,487] INFO:Ensuring source site DOM Integrity
[MainThread::2023-01-06 21:44:14,487] DEBUG:> checking CategoryListing
[MainThread::2023-01-06 21:44:14,762] WARNING:PAUSING requests for 15min
[MainThread::2023-01-06 21:44:14,764] ERROR:FAILED. An error occurred: #content_wrapper not found
[MainThread::2023-01-06 21:44:14,764] ERROR:#content_wrapper not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/entrypoint.py", line 225, in main
    sys.exit(scraper.run())
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 911, in run
    self.check_dom_integrity()
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 841, in check_dom_integrity
    raise DomIntegrityError("#content_wrapper not found")
wikihow2zim.scraper.DomIntegrityError: #content_wrapper not found
```

Looks like again a change on upstream

**Comment by rgaudin** [comment]
Looks like it was an issue upstream as following run passed 👍
