### ISSUE TITLE
TypeError: Object of type Response is not JSON serializable

### ISSUE THREAD

**Issue by kelson42** [openzim/wikihow#148]
From https://farm.openzim.org/pipeline/b034991286c2b0edf2546446/debug

```
[MainThread::2023-04-24 10:52:42,520] DEBUG:-> article: Read-Clothing-Care-Labels
[MainThread::2023-04-24 10:52:42,520] DEBUG:-> article: Prevent-Laundry-from-Bleeding
[MainThread::2023-04-24 10:52:42,520] DEBUG:-> article: Prevent-Static-in-Laundry
[MainThread::2023-04-24 10:52:42,521] DEBUG:-> article: Reduce-Laundry
[MainThread::2023-04-24 10:52:42,521] DEBUG:-> article: Remove-an-Ink-Stain-from-a-Dryer-Drum
[MainThread::2023-04-24 10:52:42,521] DEBUG:-> article: Remove-Chewing-Gum-from-a-Dryer-Drum
[MainThread::2023-04-24 10:52:42,521] DEBUG:-> article: Prevent-Clothes-from-Shrinking
[MainThread::2023-04-24 10:52:42,521] DEBUG:-> article: Prevent-Hanger-Marks-on-Shoulders
[MainThread::2023-04-24 10:52:46,671] DEBUG:-> article: Remove-Salt-Build-up-on-a-Zipper
[MainThread::2023-04-24 10:52:46,671] DEBUG:-> article: Shrink-a-Cotton-T-Shirt
[MainThread::2023-04-24 10:52:46,671] DEBUG:-> article: Remove-Static-Electricity
[MainThread::2023-04-24 10:52:46,671] DEBUG:-> article: Remove-the-Scent-of-Detergent-or-Fabric-Softener-from-Clothing
[MainThread::2023-04-24 10:52:46,671] DEBUG:-> article: Save-Energy-in-the-Laundry
[MainThread::2023-04-24 10:52:46,672] DEBUG:-> article: Save-Money-on-Laundry
[MainThread::2023-04-24 10:52:46,672] DEBUG:-> article: Save-on-Dry-Cleaning
[MainThread::2023-04-24 10:52:46,672] DEBUG:-> article: Repair-a-Curver-Washing-Basket
[MainThread::2023-04-24 10:52:46,672] DEBUG:-> article: Remove-Formaldehyde-from-Clothing
[MainThread::2023-04-24 10:52:46,672] DEBUG:-> article: Remove-Coffee-Stains-From-a-White-Shirt-Video
[MainThread::2023-04-24 10:52:50,817] DEBUG:-> article: Shrink-Cotton-Fabrics
[MainThread::2023-04-24 10:52:50,817] DEBUG:-> article: Soften-Towels
[MainThread::2023-04-24 10:52:50,817] DEBUG:-> article: Shrink-Polyester
[MainThread::2023-04-24 10:52:50,817] DEBUG:-> article: Shrink-Clothes
[MainThread::2023-04-24 10:52:50,817] DEBUG:-> article: Shrink-Rayon
[MainThread::2023-04-24 10:52:50,818] DEBUG:-> article: Shrink-a-Sweatshirt
[MainThread::2023-04-24 10:52:50,818] DEBUG:-> article: Shrink-Joggers
[MainThread::2023-04-24 10:52:50,818] DEBUG:-> article: Shrink-a-Wool-Sweater
[MainThread::2023-04-24 10:52:50,818] DEBUG:-> article: Shrink-Clothes-in-the-Dryer
[MainThread::2023-04-24 10:52:50,818] DEBUG:-> article: Shrink-Scrubs
[MainThread::2023-04-24 10:52:54,963] DEBUG:-> article: Sort-Laundry-by-Colors
[MainThread::2023-04-24 10:52:54,963] DEBUG:-> article: Start-a-Dry-Cleaning-Business
[MainThread::2023-04-24 10:52:54,963] DEBUG:-> article: Sort-Laundry
[MainThread::2023-04-24 10:52:54,963] DEBUG:-> article: Stretch-Clothes
[MainThread::2023-04-24 10:52:54,963] DEBUG:-> article: Use-a-Coin‐Operated-Washer
[MainThread::2023-04-24 10:52:54,963] DEBUG:-> article: Use-a-Laundromat
[MainThread::2023-04-24 10:52:54,963] DEBUG:-> article: Unclog-a-Dryer-Vent
[MainThread::2023-04-24 10:52:54,964] DEBUG:-> article: Unclog-a-Washing-Machine
[MainThread::2023-04-24 10:52:54,964] DEBUG:-> article: Store-a-Wet-Towel-After-Going-to-the-Gym
[MainThread::2023-04-24 10:52:54,964] DEBUG:-> article: Steam-Out-Wrinkles
[MainThread::2023-04-24 10:52:59,111] DEBUG:-> article: Use-up-Bits-of-Hand-Soaps-for-Laundry
[MainThread::2023-04-24 10:52:59,112] DEBUG:-> article: Use-a-Washing-Machine
[MainThread::2023-04-24 10:52:59,112] DEBUG:-> article: Use-a-Tide-to-Go-Pen
[MainThread::2023-04-24 10:52:59,112] DEBUG:-> article: Use-a-Public-Laundry-Room-Without-Embarrassment
[MainThread::2023-04-24 10:52:59,112] DEBUG:-> article: Use-a-Portable-Washing-Machine
[MainThread::2023-04-24 10:52:59,112] DEBUG:-> article: Use-Dryer-Sheets-Outside-the-Laundry-Room
[MainThread::2023-04-24 10:52:59,112] DEBUG:-> article: Use-Tide-Pods
[MainThread::2023-04-24 10:52:59,112] DEBUG:-> article: Use-Bleach-when-Doing-Your-Laundry
[MainThread::2023-04-24 10:52:59,112] DEBUG:-> article: Wash-a-Dry-Clean-Only-Coat-at-Home
[MainThread::2023-04-24 10:52:59,113] DEBUG:-> article: Use-Oxiclean
[MainThread::2023-04-24 10:53:03,264] DEBUG:-> article: Wash-a-Dry-Clean-Only-Garment
[MainThread::2023-04-24 10:53:03,264] DEBUG:-> article: Wash-an-Eno-Hammock
[MainThread::2023-04-24 10:53:03,264] DEBUG:-> article: Wash-a-Fleece-Jacket
[MainThread::2023-04-24 10:53:03,265] DEBUG:-> article: Wash-a-Jean-Jacket
[MainThread::2023-04-24 10:53:03,265] DEBUG:-> article: Wash-a-Silk-Pillowcase
[MainThread::2023-04-24 10:53:03,265] DEBUG:-> article: Wash-a-Linen-Jacket
[MainThread::2023-04-24 10:53:03,265] DEBUG:-> article: Wash-an-Army-Uniform
[MainThread::2023-04-24 10:53:03,265] DEBUG:-> article: Wash-Chenille
[MainThread::2023-04-24 10:53:03,265] DEBUG:-> article: Wash-Cut-Resistant-Gloves
[MainThread::2023-04-24 10:53:03,266] DEBUG:-> article: Wash-Barefoot-Dreams-Blanket
[MainThread::2023-04-24 10:53:07,410] DEBUG:-> article: Wash-Towels
[MainThread::2023-04-24 10:53:07,411] DEBUG:-> article: Wash-New-Towels
[MainThread::2023-04-24 10:53:07,411] DEBUG:-> article: Wash-Darks-and-Lights-Together
[MainThread::2023-04-24 10:53:07,411] DEBUG:-> article: Wash-Knitted-Blankets
[MainThread::2023-04-24 10:53:07,411] DEBUG:-> article: Wash-Trainers-in-the-Washing-Machine
[MainThread::2023-04-24 10:53:07,411] DEBUG:-> article: Wash-Nugget-Cover
[MainThread::2023-04-24 10:53:07,411] DEBUG:-> article: What-Is-Permanent-Press
[MainThread::2023-04-24 10:53:09,414] DEBUG:Category: Gas Plumbing
[MainThread::2023-04-24 10:53:11,535] DEBUG:Removing /output/www.wikihow.com_kn5prdaa
[MainThread::2023-04-24 10:53:11,546] ERROR:FAILED. An error occurred: Object of type Response is not JSON serializable
[MainThread::2023-04-24 10:53:11,546] ERROR:Object of type Response is not JSON serializable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 973, in run
    self.build_expected_articles()
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 358, in build_expected_articles
    for query in self.api_site.query(
  File "/usr/local/lib/python3.8/site-packages/pywikiapi/Site.py", line 310, in iterate
    result = self(action, **req)
  File "/usr/local/lib/python3.8/site-packages/pywikiapi/Site.py", line 130, in __call__
    response = self.request(method, **request_kw)
  File "/usr/local/lib/python3.8/site-packages/pywikiapi/Site.py", line 423, in request
    raise ApiError('Call failed', r)
pywikiapi.utils.ApiError: <unprintable ApiError object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/entrypoint.py", line 225, in main
    sys.exit(scraper.run())
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 1007, in run
    logger.error(f"Interrupting process due to error: {exc}")
  File "/usr/local/lib/python3.8/site-packages/pywikiapi/utils.py", line 15, in __str__
    return self.message + ': ' + json.dumps(self.data)
  File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable

```

**Comment by rgaudin** [comment]
Relaunched it and it worked: https://farm.openzim.org/pipeline/75473fd8-0a40-41fc-abfe-073849369b8c

**Comment by kelson42** [comment]
This happens time to time, we should better do a proper handling IMO.

**Comment by benoit74** [comment]
Fixed by https://github.com/openzim/pywikiapi/pull/2
