### ISSUE TITLE
Issues around category processing

### ISSUE THREAD

**Issue by benoit74** [openzim/wikihow#154]
At least in [wikihow_en_endless_arts-and-entertainment](https://farm.openzim.org/recipes/wikihow_en_endless_arts-and-entertainment), the scraper is failing to scrape a category and stopping immediately:

```
[MainThread::2024-01-31 21:40:08,618] INFO:> Category:Painting Walls
[MainThread::2024-01-31 21:40:08,843] DEBUG:URL `https://www.wikihow.com/images/thumb/f/fc/Paint-over-Varnish-Step-11.jpg/-crop-375-300-375px-nowatermark-Paint-over-Varnish-Step-11.jpg.webp` already processed.
[MainThread::2024-01-31 21:40:08,885] DEBUG:> assets/2750523058.css
[MainThread::2024-01-31 21:40:08,893] INFO:> Category:Home Theater
[MainThread::2024-01-31 21:40:08,900] ERROR:Interrupting process due to error: list index out of range
[MainThread::2024-01-31 21:40:08,900] ERROR:list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 985, in run
    self.scrape_categories()
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 514, in scrape_categories
    self.scrape_category(category)
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 518, in scrape_category
    nb_pages = self.scrape_category_page(category, page_num=1)
  File "/usr/local/lib/python3.8/site-packages/wikihow2zim-1.2.2-py3.8.egg/wikihow2zim/scraper.py", line 547, in scrape_category_page
    content = soup.select("div#content_wrapper")[0]
IndexError: list index out of range
```

This is done after all articles processing, which poses the question of whether something is feasible/desirable to avoid loosing everything which has already succeeded, especially since it looks like the categories are now fetched from the API at the very beginning of the scrape.

Another sub-issue is that it looks many categories do not exist (or at least we fail to fetch them):
```
[MainThread::2024-01-31 21:40:07,954] INFO:> Category:Faux Painting and Faux Finishes
[MainThread::2024-01-31 21:40:08,282] ERROR:Giving up fetch(...) after 1 tries (requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.wikihow.com/Category:Faux-Painting-and-Faux-Finishes)
[MainThread::2024-01-31 21:40:08,282] WARNING:>>> HTTP 404, skipping.
[MainThread::2024-01-31 21:40:08,282] INFO:> Category:Costumes for Dogs
[MainThread::2024-01-31 21:40:08,618] ERROR:Giving up fetch(...) after 1 tries (requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.wikihow.com/Category:Costumes-for-Dogs)
[MainThread::2024-01-31 21:40:08,618] WARNING:>>> HTTP 404, skipping.
```

**Comment by benoit74** [comment]
The first error which stops the scraping is not reproduced locally. It is probably linked to #157.

Missing categories is ... normal (at least reflecting the reality).

Closing the issue for now.
